name: CI

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install Dependencies
        run: yarn install

      - name: Run ESLint
        run: yarn lint

      - name: Run Tests:unit
        run: yarn test

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build
